### ISSUE TITLE
Web server proxy for safe access to Azure Storage?

### ISSUE THREAD

**Issue by vermorel** [titanium007/Titanium-Web-Proxy#17]
The Titanium project is very interesting, and I have a specific scenario in mind for the Azure Storage. I would like some guidance to figure out if Titanium can be used for this scenario.

The Azure Storage (blobs, queues, tables) is great but the storage keys only comes as _read+write_. Yet, for many scenarios it would be much safer to have only a _read_ access (ex: backup agent, production monitoring agent, etc). Indeed, a _read+write_ access to a production system is inherently risky.

Thus, I am considering a setup that involves the HTTP proxy. The proxy would only forward the _safe_ requests with a filter the HTTP verbs; plus the proxy would perform a API key replacement as well. So that the proxied agent hold only proxy keys and not real storage keys.

In order to avoid mishaps relative to the keys _read+write_, the HTTP proxy is intended to be hosted on Azure itself, and fully isolated from all proxied agents. The agent never gets any access to the real storage keys, only to the proxy keys. This prevents any destructive behavior from the proxied agents.

Now _this flavor_ of HTTP proxy is intended to inbound HTTP traffic; while the current Titanium flavor seems to capture output HTTP traffic. 

Could someone shed some light on how Titanium could be used in such a scenario?  Thanks!

**Comment by titanium007** [comment]
You are probably talking about making this  a transparent proxy, where client is unaware of the existence of a proxy. 

Couple of tweaks need to be done, especially for HTTPS since the assumption is client would send CONNECT request.

**Comment by vermorel** [comment]
Well actually the client would be making HTTP request to `public.example.com` which would, in turn, repost the HTTP requests to `private.example.com`. The originating client could be sitting anywhere on the internet in this scenario. Does it make sense?

**Comment by titanium007** [comment]
Yes. You can make this proxy listen to port 80 on private.example.com. However only HTTP requests would work. 

If you don't want to use port 80 you can use listen on some other port, and then let public.example.com forward it to that port.

**Comment by titanium007** [comment]
Transparent EndPoints are now Supported with version 2.1. However Server Name Indication is not supported yet. Closing this.
