### ISSUE TITLE
System-wide proxy settings are not always reset on stopping

### ISSUE THREAD

**Issue by rgripper** [titanium007/Titanium-Web-Proxy#30]
If there is no EnableAutoproxyResultCache registry key or it is set to 1, the proxy settings in the registry are not going to be reset after proxy is stopped.

**Comment by titanium007** [comment]
I am using windows 10. By default I don't have EnableAutoproxyResultCache registry value set. The proxy resets fine when stopped. I tested by adding EnableAutoproxyResultCache with value 1. Didn't make a difference.

**Comment by rgripper** [comment]
MB smth else was also set up by admins I don't know about. Ok, closing for the time being.
