### ISSUE TITLE
Response character set error

### ISSUE THREAD

**Issue by mergoktas** [titanium007/Titanium-Web-Proxy#31]
In file ResponseHandler.cs line 105
```
response.Response.CharacterSet = response.Response.ResponseHeaders[i].Value.Split(';')[1].ToLower().Replace("charset=", string.Empty).Trim();
```
On machines which have different locale settings other than english, ToLower() function causes problem like it converts ISO-8859-9 to ıso-8859-9 which is Turkish and not a correct defininition for char set.

Please notice that **ıso-8859-9** is not **iso-8859-1**. 
I removed ToLower() like below and it works.
```
response.Response.CharacterSet = response.Response.ResponseHeaders[i].Value.Split(';')[1].Replace("charset=", string.Empty).Trim();
```

**Comment by titanium007** [comment]
This has been address in [release branch](https://github.com/titanium007/Titanium-Web-Proxy/tree/release)
