### ISSUE TITLE
excluded host are not allowed

### ISSUE THREAD

**Issue by mergoktas** [titanium007/Titanium-Web-Proxy#32]
if an host name is in the excluded list like
ProxyServer.ExcludedHttpsHostNameRegex.Add(".youtube.com");
then proxy closing down the connection. Then it is not possible to access the website.
In our case youtube. Please test the proxy with above line.

I think, it should just by pass the request directly to server if it is  in the excluded list.
Like a by pass proxy. If it is not in the excluded list then we should be able to modify the request and response, Am I right or mistaken?

**Comment by titanium007** [comment]
As the name indicates the exclusion is only valid for **https** requests. The browser realizes that its talking to a proxy not to the server. So each time it initiates a secure connection, it expects the proxy to tunnel the request by sending something like CONNECT youtube.com. However we trick the browser by lying to it that we are tunneling the request, but in reality we fake it with self-signed server certificate.

So in short if you are accessing to youtube.com on http://youtube.com the proxy won't exclude the request. (Notice that request body is always relayed unless you decide to read it). However if youtube.com is in the **ExcludedHttpsHostNameRegex** list then all Https connections to youtube will be relayed. You won't see that in request/response event handlers. 

That is the expectation, but as you reported its not working properly as we expect.

**Comment by titanium007** [comment]
This has been address in [release branch](https://github.com/titanium007/Titanium-Web-Proxy/tree/release)
