### ISSUE TITLE
Response CharacterSet Binary Problem

### ISSUE THREAD

**Issue by LostMann** [titanium007/Titanium-Web-Proxy#35]
Hi,
i try to open this image and so i found an error in HttpWebResponseExtensions->GetResponseEncoding method. It throws exception because of response.Response.CharacterSet="binary". So i surrond the code with try catch block and in catch block I return a default CharacterSet.

URL: http://trthaberstatic.s3-website-eu-west-1.amazonaws.com/resimler/532000/532980.jpg

**Comment by titanium007** [comment]
This has been address in [release branch](https://github.com/titanium007/Titanium-Web-Proxy/tree/release)
