### ISSUE TITLE
Sites with alternate SSL port will not load when using a proxy

### ISSUE THREAD

**Issue by brondavies** [titanium007/Titanium-Web-Proxy#36]
I debug and test on an alternate SSL port so for instance https://qa.example.com:4444/ would be the target for my Selenium test suite whereas https://www.example.com/ would be the real enchilada.  It seems that due to this logic: https://github.com/titanium007/Titanium-Web-Proxy/blob/a88c68c4b64b8988153d3728ec8c721d38310600/Titanium.Web.Proxy/RequestHandler.cs#L57 the proxy isn't working on another port other than the default SSL port.  Either we need to be able to supply a list of alternate ports to consider as SSL in the ProxyServer configuration or come up with a better way to detect an SSL request.

**Comment by titanium007** [comment]
I agree this is a problem. And appreciate your PR. However in the long run I am thinking of adding a collection of EndPoints like what we see in FiddlerCore. The advantage there is that we can add endpoints for transparent proxy (where client is not aware of a proxy).

**Comment by brondavies** [comment]
I we can look defining an API for endpoints, I'll be happy to contribute.  This is a great way to make feature/unit tests mock responses from external sites without a lot of configuration and hoops to jump through.

**Comment by titanium007** [comment]
Yes that would be great.

**Comment by titanium007** [comment]
This has been address in [release branch](https://github.com/titanium007/Titanium-Web-Proxy/tree/release)
